# Generated by Django 5.2.12 on 2026-07-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_sc_logo_ticket_passenger_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
