# Generated by Django 5.2.12 on 2026-07-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_ticket_is_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="boa_account",
            field=models.CharField(
                blank=True,
                max_length=25,
                null=True,
                verbose_name="Bank of Abyssinia Account",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="cbe_account",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="CBE Account Number"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Is Approved/Active"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="telebirr_account",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Telebirr Number"
            ),
        ),
    ]
